{
  "info": {
    "author": "Bright Interactive",
    "author_email": "francis@bright-interactive.co.uk",
    "bugtrack_url": "",
    "classifiers": [],
    "description": "UNKNOWN",
    "docs_url": null,
    "download_url": "UNKNOWN",
    "downloads": {
      "last_day": 0,
      "last_month": 0,
      "last_week": 0
    },
    "home_page": "http://github.com/brightinteractive/django-raise-exception-view/",
    "keywords": null,
    "license": "BSD",
    "maintainer": null,
    "maintainer_email": null,
    "name": "django-raise-exception-view",
    "platform": "UNKNOWN",
    "project_url": "https://pypi.org/project/django-raise-exception-view/",
    "release_url": "https://pypi.org/project/django-raise-exception-view/1.0.1/",
    "requires_python": null,
    "summary": "Django view that raises an exception so you can test your logging setup",
    "version": "1.0.1"
  },
  "releases": {
    "1.0.0": [
      {
        "comment_text": "",
        "digests": {
          "md5": "a586010707d43857919ce4dd2c56588c",
          "sha256": "83bff46d513fc1e297198982ee9747b27f2968ad035f5042673138662351bfe2"
        },
        "downloads": 2930,
        "filename": "django-raise-exception-view-1.0.0.tar.gz",
        "has_sig": false,
        "md5_digest": "a586010707d43857919ce4dd2c56588c",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 2073,
        "upload_time": "2012-04-13T12:23:46",
        "url": "https://files.pythonhosted.org/packages/61/d3/2c9d0e2ee9c22bd60aad9a5624d02e9bbd941bd384c7630adc2353707307/django-raise-exception-view-1.0.0.tar.gz"
      }
    ],
    "1.0.1": [
      {
        "comment_text": "",
        "digests": {
          "md5": "88e2eb0202a60f790c00cf1986feaa8f",
          "sha256": "63dff4c5a8209a4be0139e82478d6dc2b9197c641f34047fb9d9d68bcfca344b"
        },
        "downloads": 3230,
        "filename": "django-raise-exception-view-1.0.1.tar.gz",
        "has_sig": false,
        "md5_digest": "88e2eb0202a60f790c00cf1986feaa8f",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 2077,
        "upload_time": "2012-04-13T12:27:48",
        "url": "https://files.pythonhosted.org/packages/1c/ea/0c67c37ab96887b8e9d933f27100c95aa34bce3ae611104b6faf48f40d96/django-raise-exception-view-1.0.1.tar.gz"
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "md5": "88e2eb0202a60f790c00cf1986feaa8f",
        "sha256": "63dff4c5a8209a4be0139e82478d6dc2b9197c641f34047fb9d9d68bcfca344b"
      },
      "downloads": 3230,
      "filename": "django-raise-exception-view-1.0.1.tar.gz",
      "has_sig": false,
      "md5_digest": "88e2eb0202a60f790c00cf1986feaa8f",
      "packagetype": "sdist",
      "python_version": "source",
      "size": 2077,
      "upload_time": "2012-04-13T12:27:48",
      "url": "https://files.pythonhosted.org/packages/1c/ea/0c67c37ab96887b8e9d933f27100c95aa34bce3ae611104b6faf48f40d96/django-raise-exception-view-1.0.1.tar.gz"
    }
  ]
}