{
  "info": {
    "author": "PokestarFan",
    "author_email": "pokestarfan@yahoo.com",
    "bugtrack_url": null,
    "classifiers": [],
    "description": "UNKNOWN\n\n\n",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": 0,
      "last_month": 0,
      "last_week": 0
    },
    "home_page": "https://github.com/Poketec/ExceptionGenerator",
    "keywords": "",
    "license": "MIT",
    "maintainer": "",
    "maintainer_email": "",
    "name": "exceptiongenerator",
    "platform": "",
    "project_url": "https://pypi.org/project/exceptiongenerator/",
    "release_url": "https://pypi.org/project/exceptiongenerator/2.0/",
    "requires_dist": [],
    "requires_python": "",
    "summary": "Easy way to generate exceptions that just have a message",
    "version": "2.0"
  },
  "releases": {
    "1.0": [
      {
        "comment_text": "",
        "digests": {
          "md5": "8b9e5d7e973eee96203e372b685c1400",
          "sha256": "c2a7a95b1c81c9b7d9f3fbe83cdc37de4f1982c02cfd8e47040f9a89a3666b23"
        },
        "downloads": -1,
        "filename": "exceptiongenerator-1.0-py2.py3-none-any.whl",
        "has_sig": false,
        "md5_digest": "8b9e5d7e973eee96203e372b685c1400",
        "packagetype": "bdist_wheel",
        "python_version": "py2.py3",
        "size": 2491,
        "upload_time": "2018-01-25T21:46:20",
        "url": "https://files.pythonhosted.org/packages/51/61/519895a3ba6b77bfa5829574a344bc571ce865cfcdbdfd53738d430a1cb2/exceptiongenerator-1.0-py2.py3-none-any.whl"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "d5bce0d57de750b043ae5a8411b844ee",
          "sha256": "e5de6947f83bc746000c1bcb7f79eedd9b972cd15b5c65340dedab0a09fb8a4c"
        },
        "downloads": -1,
        "filename": "exceptiongenerator-1.0-py3.6.egg",
        "has_sig": false,
        "md5_digest": "d5bce0d57de750b043ae5a8411b844ee",
        "packagetype": "bdist_egg",
        "python_version": "3.6",
        "size": 1719,
        "upload_time": "2018-01-25T21:46:22",
        "url": "https://files.pythonhosted.org/packages/43/21/a5a0f5f21d190896a2e349e49c2a10b1efdff4627724fc346acbadbbdcdc/exceptiongenerator-1.0-py3.6.egg"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "a5f45882a775b9b452ad803fd026597f",
          "sha256": "57630492e808428f60b120ba983f6811e88abe02776064786a2962c4adb84aee"
        },
        "downloads": -1,
        "filename": "exceptiongenerator-1.0.tar.gz",
        "has_sig": false,
        "md5_digest": "a5f45882a775b9b452ad803fd026597f",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 1015,
        "upload_time": "2018-01-25T21:46:24",
        "url": "https://files.pythonhosted.org/packages/43/08/fcccb1612b3b86688f2cbf6ad3ca9223785eaa8044273c629970119a1922/exceptiongenerator-1.0.tar.gz"
      }
    ],
    "2.0": [
      {
        "comment_text": "",
        "digests": {
          "md5": "fff2ab63ce72ab154818871ca678e854",
          "sha256": "04c625ce446b5d3edceffc0c239e88aa0138ea488c09f6cb86ddf2365d7612b0"
        },
        "downloads": -1,
        "filename": "exceptiongenerator-2.0-py2.py3-none-any.whl",
        "has_sig": false,
        "md5_digest": "fff2ab63ce72ab154818871ca678e854",
        "packagetype": "bdist_wheel",
        "python_version": "py2.py3",
        "size": 2542,
        "upload_time": "2018-01-26T02:03:23",
        "url": "https://files.pythonhosted.org/packages/09/2b/6c49bc7a080ec36854aa165e5821051c3bc411cfd83834ab63674387262c/exceptiongenerator-2.0-py2.py3-none-any.whl"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "ddf6b9df4af27d9cfbcda23ed3c85147",
          "sha256": "fc8732c0ab592b5eba5dbe40076c686e05d971360ecdea5e95f004d38e536564"
        },
        "downloads": -1,
        "filename": "exceptiongenerator-2.0-py3.6.egg",
        "has_sig": false,
        "md5_digest": "ddf6b9df4af27d9cfbcda23ed3c85147",
        "packagetype": "bdist_egg",
        "python_version": "3.6",
        "size": 1840,
        "upload_time": "2018-01-26T02:03:24",
        "url": "https://files.pythonhosted.org/packages/35/ea/c5783af0d69f6768612e714a2330cae496211fa43a7e921a7e3a2adad277/exceptiongenerator-2.0-py3.6.egg"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "c27469638c03de7bbd90a15364b484a2",
          "sha256": "4c7062b5e5d2e5f647bd9fa5c838aef95afbe3b3298902fb2a8e3d92792cfa55"
        },
        "downloads": -1,
        "filename": "exceptiongenerator-2.0.tar.gz",
        "has_sig": false,
        "md5_digest": "c27469638c03de7bbd90a15364b484a2",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 1090,
        "upload_time": "2018-01-26T02:03:25",
        "url": "https://files.pythonhosted.org/packages/40/f6/b20842c5e0e39c25d2b6fdb07fb444ed54241faea2d55b100c9fe3a97dd4/exceptiongenerator-2.0.tar.gz"
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "md5": "fff2ab63ce72ab154818871ca678e854",
        "sha256": "04c625ce446b5d3edceffc0c239e88aa0138ea488c09f6cb86ddf2365d7612b0"
      },
      "downloads": -1,
      "filename": "exceptiongenerator-2.0-py2.py3-none-any.whl",
      "has_sig": false,
      "md5_digest": "fff2ab63ce72ab154818871ca678e854",
      "packagetype": "bdist_wheel",
      "python_version": "py2.py3",
      "size": 2542,
      "upload_time": "2018-01-26T02:03:23",
      "url": "https://files.pythonhosted.org/packages/09/2b/6c49bc7a080ec36854aa165e5821051c3bc411cfd83834ab63674387262c/exceptiongenerator-2.0-py2.py3-none-any.whl"
    },
    {
      "comment_text": "",
      "digests": {
        "md5": "ddf6b9df4af27d9cfbcda23ed3c85147",
        "sha256": "fc8732c0ab592b5eba5dbe40076c686e05d971360ecdea5e95f004d38e536564"
      },
      "downloads": -1,
      "filename": "exceptiongenerator-2.0-py3.6.egg",
      "has_sig": false,
      "md5_digest": "ddf6b9df4af27d9cfbcda23ed3c85147",
      "packagetype": "bdist_egg",
      "python_version": "3.6",
      "size": 1840,
      "upload_time": "2018-01-26T02:03:24",
      "url": "https://files.pythonhosted.org/packages/35/ea/c5783af0d69f6768612e714a2330cae496211fa43a7e921a7e3a2adad277/exceptiongenerator-2.0-py3.6.egg"
    },
    {
      "comment_text": "",
      "digests": {
        "md5": "c27469638c03de7bbd90a15364b484a2",
        "sha256": "4c7062b5e5d2e5f647bd9fa5c838aef95afbe3b3298902fb2a8e3d92792cfa55"
      },
      "downloads": -1,
      "filename": "exceptiongenerator-2.0.tar.gz",
      "has_sig": false,
      "md5_digest": "c27469638c03de7bbd90a15364b484a2",
      "packagetype": "sdist",
      "python_version": "source",
      "size": 1090,
      "upload_time": "2018-01-26T02:03:25",
      "url": "https://files.pythonhosted.org/packages/40/f6/b20842c5e0e39c25d2b6fdb07fb444ed54241faea2d55b100c9fe3a97dd4/exceptiongenerator-2.0.tar.gz"
    }
  ]
}