{
  "info": {
    "author": "wanliguhong",
    "author_email": "UNKNOWN",
    "bugtrack_url": null,
    "classifiers": [],
    "description": "UNKNOWN",
    "docs_url": null,
    "download_url": "UNKNOWN",
    "downloads": {
      "last_day": 0,
      "last_month": 0,
      "last_week": 0
    },
    "home_page": "http://pypi.python.org/",
    "keywords": null,
    "license": "UNKNOWN",
    "maintainer": null,
    "maintainer_email": null,
    "name": "hcl_exception.py",
    "platform": "UNKNOWN",
    "project_url": "https://pypi.org/project/hcl_exception.py/",
    "release_url": "https://pypi.org/project/hcl_exception.py/1.0.0/",
    "requires_python": null,
    "summary": "char data.",
    "version": "1.0.0"
  },
  "releases": {
    "1.0.0": [
      {
        "comment_text": "",
        "digests": {
          "md5": "232e8002dae38d7acdaa23e79b61893e",
          "sha256": "7513f4e9a46331bf369b33f47d9c9e2e576ad7584c17a9653d9f0b1bda7c8d68"
        },
        "downloads": 3077,
        "filename": "hcl_exception.py-1.0.0.tar.gz",
        "has_sig": false,
        "md5_digest": "232e8002dae38d7acdaa23e79b61893e",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 729,
        "upload_time": "2012-06-10T20:08:12",
        "url": "https://files.pythonhosted.org/packages/27/9c/2a5de6fd40e948908fb3dcf63aba68bd278037d7dc10541a06d7af1da7d2/hcl_exception.py-1.0.0.tar.gz"
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "md5": "232e8002dae38d7acdaa23e79b61893e",
        "sha256": "7513f4e9a46331bf369b33f47d9c9e2e576ad7584c17a9653d9f0b1bda7c8d68"
      },
      "downloads": 3077,
      "filename": "hcl_exception.py-1.0.0.tar.gz",
      "has_sig": false,
      "md5_digest": "232e8002dae38d7acdaa23e79b61893e",
      "packagetype": "sdist",
      "python_version": "source",
      "size": 729,
      "upload_time": "2012-06-10T20:08:12",
      "url": "https://files.pythonhosted.org/packages/27/9c/2a5de6fd40e948908fb3dcf63aba68bd278037d7dc10541a06d7af1da7d2/hcl_exception.py-1.0.0.tar.gz"
    }
  ]
}