{
  "info": {
    "author": "Hugo Wainwright",
    "author_email": "wainwrighthugo@gmail.com",
    "bugtrack_url": null,
    "classifiers": [],
    "description": "UNKNOWN",
    "docs_url": null,
    "download_url": "https://github.com/frugs/retryget/tarball/0.0.2",
    "downloads": {
      "last_day": 0,
      "last_month": 0,
      "last_week": 0
    },
    "home_page": "https://github.com/frugs/retryget",
    "keywords": "retry,retry,get,fallback",
    "license": "UNKNOWN",
    "maintainer": null,
    "maintainer_email": null,
    "name": "retryfallback",
    "platform": "UNKNOWN",
    "project_url": "https://pypi.org/project/retryfallback/",
    "release_url": "https://pypi.org/project/retryfallback/0.0.2/",
    "requires_python": null,
    "summary": "Utility for wrapping unsafe calls with a retry mechanism",
    "version": "0.0.2"
  },
  "releases": {
    "0.0.2": [
      {
        "comment_text": "",
        "digests": {
          "md5": "d8a567741abfbf69ef81cf4d3a95289c",
          "sha256": "1f15b1da6b16c76a6094ad2d076193ae5e332a2d3dba5855c20147c5951108e3"
        },
        "downloads": 48,
        "filename": "retryfallback-0.0.2.tar.gz",
        "has_sig": false,
        "md5_digest": "d8a567741abfbf69ef81cf4d3a95289c",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 993,
        "upload_time": "2016-12-08T10:34:21",
        "url": "https://files.pythonhosted.org/packages/68/72/54898ba468621ffb0c88800c41ae08e7aa87f0a5f27accb750dcfdeb8035/retryfallback-0.0.2.tar.gz"
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "md5": "d8a567741abfbf69ef81cf4d3a95289c",
        "sha256": "1f15b1da6b16c76a6094ad2d076193ae5e332a2d3dba5855c20147c5951108e3"
      },
      "downloads": 48,
      "filename": "retryfallback-0.0.2.tar.gz",
      "has_sig": false,
      "md5_digest": "d8a567741abfbf69ef81cf4d3a95289c",
      "packagetype": "sdist",
      "python_version": "source",
      "size": 993,
      "upload_time": "2016-12-08T10:34:21",
      "url": "https://files.pythonhosted.org/packages/68/72/54898ba468621ffb0c88800c41ae08e7aa87f0a5f27accb750dcfdeb8035/retryfallback-0.0.2.tar.gz"
    }
  ]
}