{
  "info": {
    "author": "Huang Jiangbin",
    "author_email": "dobetter@zencore.cn",
    "bugtrack_url": null,
    "classifiers": [
      "Development Status :: 5 - Production/Stable",
      "Intended Audience :: Developers",
      "License :: OSI Approved :: MIT License",
      "Programming Language :: Python :: 3",
      "Programming Language :: Python :: 3 :: Only",
      "Topic :: Software Development :: Libraries :: Python Modules"
    ],
    "description": "zenore-errors\n=============\n\n.. image:: https://travis-ci.org/zencore-dobetter/zencore-errors.svg?branch=master\n    :target: https://travis-ci.org/zencore-dobetter/zencore-errors\n\nZencore error code collection.\n\n\n",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": 0,
      "last_month": 0,
      "last_week": 0
    },
    "home_page": "https://github.com/zencore-dobetter/zencore-errors",
    "keywords": "zencore-errors",
    "license": "MIT",
    "maintainer": "",
    "maintainer_email": "",
    "name": "zencore-errors",
    "platform": "",
    "project_url": "https://pypi.org/project/zencore-errors/",
    "release_url": "https://pypi.org/project/zencore-errors/2.0.7/",
    "requires_dist": [],
    "requires_python": "",
    "summary": "Zencore error code collection",
    "version": "2.0.7"
  },
  "releases": {
    "1.0.4": [
      {
        "comment_text": "",
        "digests": {
          "md5": "f22824df67da7137c4565e3595f27fd4",
          "sha256": "ee15e8d03bb626560b183c1a30e12013c0458f5d93da44d440fe4c305be14e1b"
        },
        "downloads": -1,
        "filename": "zencore-errors-1.0.4.tar.gz",
        "has_sig": false,
        "md5_digest": "f22824df67da7137c4565e3595f27fd4",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 2253,
        "upload_time": "2017-08-10T14:04:23",
        "url": "https://files.pythonhosted.org/packages/d0/23/e7f1efe3ed3befcf9a144e83f76b668b5addfab9198d7a01dcbf2ca6711c/zencore-errors-1.0.4.tar.gz"
      }
    ],
    "1.0.5": [
      {
        "comment_text": "",
        "digests": {
          "md5": "9df49a4be92747ea5563e7e9c9a0d986",
          "sha256": "12fb7da61d8a4272dcbae9f00fc18969d3d918c408e389ae7cb02e69bb34c65f"
        },
        "downloads": -1,
        "filename": "zencore-errors-1.0.5.tar.gz",
        "has_sig": false,
        "md5_digest": "9df49a4be92747ea5563e7e9c9a0d986",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 2274,
        "upload_time": "2017-09-18T14:52:19",
        "url": "https://files.pythonhosted.org/packages/b9/3f/79f5ec67323d44f29e46458711d88ac996ebdd451b6b9d666dd3322cbcfa/zencore-errors-1.0.5.tar.gz"
      }
    ],
    "2.0.0": [
      {
        "comment_text": "",
        "digests": {
          "md5": "77db6faa0a2f191e077c01e3bdbb6997",
          "sha256": "fe76894fc0c440704fb03015b379a56c9a6dbe2535a2832d0108de25d35d0042"
        },
        "downloads": -1,
        "filename": "zencore-errors-2.0.0.tar.gz",
        "has_sig": false,
        "md5_digest": "77db6faa0a2f191e077c01e3bdbb6997",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 2700,
        "upload_time": "2017-09-27T13:51:20",
        "url": "https://files.pythonhosted.org/packages/42/03/4770db09ff60104b95c86b6a8e18695c87f9b2191c00a545330b43f24636/zencore-errors-2.0.0.tar.gz"
      }
    ],
    "2.0.1": [
      {
        "comment_text": "",
        "digests": {
          "md5": "b01245f4a14b9b94e080f462295f819b",
          "sha256": "cc7ccd78f8b6e7fbe5f1683c8f803c56a9ca8d230f8ba7d987ec1b5e6a7b8045"
        },
        "downloads": -1,
        "filename": "zencore-errors-2.0.1.tar.gz",
        "has_sig": false,
        "md5_digest": "b01245f4a14b9b94e080f462295f819b",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 3111,
        "upload_time": "2017-09-28T14:55:59",
        "url": "https://files.pythonhosted.org/packages/0b/b5/d8cee690dfc6ec1ab6af084e5bd4f4425f0781c387267b6e5a74113a7d74/zencore-errors-2.0.1.tar.gz"
      }
    ],
    "2.0.2": [
      {
        "comment_text": "",
        "digests": {
          "md5": "bebcfe37ad5e2737bb6c3fc4bb0c55b1",
          "sha256": "c11a36806a04a26890eb68148fae8ef115407f04dc1398a7c8bc84fca9effcf5"
        },
        "downloads": -1,
        "filename": "zencore-errors-2.0.2.tar.gz",
        "has_sig": false,
        "md5_digest": "bebcfe37ad5e2737bb6c3fc4bb0c55b1",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 3294,
        "upload_time": "2017-10-10T01:58:53",
        "url": "https://files.pythonhosted.org/packages/e3/44/87e13dbeb50130d2a9515a449f7333039e50ea116d40086a84dfc6f1c1ff/zencore-errors-2.0.2.tar.gz"
      }
    ],
    "2.0.3": [
      {
        "comment_text": "",
        "digests": {
          "md5": "1514d48849473263de576b50f919f2d4",
          "sha256": "655d525871d621b5a897d80acf974adf302c18248810b41b83308ca9782dd101"
        },
        "downloads": -1,
        "filename": "zencore-errors-2.0.3.tar.gz",
        "has_sig": false,
        "md5_digest": "1514d48849473263de576b50f919f2d4",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 3294,
        "upload_time": "2017-10-16T12:27:29",
        "url": "https://files.pythonhosted.org/packages/6d/67/ff3ad5f00e5908ce1d954586c32f310a11be0baf645db8d7cff7fdf968e0/zencore-errors-2.0.3.tar.gz"
      }
    ],
    "2.0.4": [
      {
        "comment_text": "",
        "digests": {
          "md5": "9db1d628d69313f3aa08a256c2495710",
          "sha256": "cc575acdda0076911eb5d54f625c2b1d36faf8565d148a41c6b01ac5fd2923f6"
        },
        "downloads": -1,
        "filename": "zencore-errors-2.0.4.tar.gz",
        "has_sig": false,
        "md5_digest": "9db1d628d69313f3aa08a256c2495710",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 3292,
        "upload_time": "2017-10-16T12:41:38",
        "url": "https://files.pythonhosted.org/packages/9f/42/3e1b7c9bbb93ee5d2041b9964c7103f513b0c739275ee854e192a368e6ee/zencore-errors-2.0.4.tar.gz"
      }
    ],
    "2.0.5": [
      {
        "comment_text": "",
        "digests": {
          "md5": "fe800faf0db6d884476732f10b9f5042",
          "sha256": "ceeb75d263016fef339059d87633b2898f6f9a3ba10bc660d5fc84736a2642aa"
        },
        "downloads": -1,
        "filename": "zencore-errors-2.0.5.tar.gz",
        "has_sig": false,
        "md5_digest": "fe800faf0db6d884476732f10b9f5042",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 3363,
        "upload_time": "2017-10-16T12:45:19",
        "url": "https://files.pythonhosted.org/packages/f8/27/f533535c1fbbaffcdcb126fea805f3042b12415a03b9ab7e79ffc959da3c/zencore-errors-2.0.5.tar.gz"
      }
    ],
    "2.0.6": [
      {
        "comment_text": "",
        "digests": {
          "md5": "757f9cf4a1450ade687f619bb9b8e761",
          "sha256": "3afca8ec7dcca1fd9e90de10b45380f4e9d474f8aeccc6c2562ebdc70232d50e"
        },
        "downloads": -1,
        "filename": "zencore-errors-2.0.6.tar.gz",
        "has_sig": false,
        "md5_digest": "757f9cf4a1450ade687f619bb9b8e761",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 3367,
        "upload_time": "2017-10-16T13:01:04",
        "url": "https://files.pythonhosted.org/packages/48/16/f49627e4892a141fc79595786d691d08214cfcc766fce80252db6656d49b/zencore-errors-2.0.6.tar.gz"
      }
    ],
    "2.0.7": [
      {
        "comment_text": "",
        "digests": {
          "md5": "a626615825cf2a63d3c67723de2780be",
          "sha256": "81259348b63f23ff5979f8910891fb8aafe5136f7eb259c0f45c23981518abfb"
        },
        "downloads": -1,
        "filename": "zencore-errors-2.0.7.tar.gz",
        "has_sig": false,
        "md5_digest": "a626615825cf2a63d3c67723de2780be",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 3364,
        "upload_time": "2017-10-16T13:07:12",
        "url": "https://files.pythonhosted.org/packages/cf/75/dc23bed30a70e947cd6fe056899de9ac6f9f73ac5c5bedc21570bc8198d6/zencore-errors-2.0.7.tar.gz"
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "md5": "a626615825cf2a63d3c67723de2780be",
        "sha256": "81259348b63f23ff5979f8910891fb8aafe5136f7eb259c0f45c23981518abfb"
      },
      "downloads": -1,
      "filename": "zencore-errors-2.0.7.tar.gz",
      "has_sig": false,
      "md5_digest": "a626615825cf2a63d3c67723de2780be",
      "packagetype": "sdist",
      "python_version": "source",
      "size": 3364,
      "upload_time": "2017-10-16T13:07:12",
      "url": "https://files.pythonhosted.org/packages/cf/75/dc23bed30a70e947cd6fe056899de9ac6f9f73ac5c5bedc21570bc8198d6/zencore-errors-2.0.7.tar.gz"
    }
  ]
}