{
  "info": {
    "author": "Huang Jiangbin",
    "author_email": "dobetter@zencore.cn",
    "bugtrack_url": null,
    "classifiers": [
      "Development Status :: 5 - Production/Stable",
      "Intended Audience :: Developers",
      "License :: OSI Approved :: MIT License",
      "Programming Language :: Python :: 3",
      "Programming Language :: Python :: 3 :: Only",
      "Topic :: Software Development :: Libraries :: Python Modules"
    ],
    "description": "zenore-errors\n=============\n\n.. image:: https://travis-ci.org/zencore-dobetter/zencore-errors.svg?branch=master\n    :target: https://travis-ci.org/zencore-dobetter/zencore-errors\n\nZencore error code collection.\n\n\n",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": 0,
      "last_month": 0,
      "last_week": 0
    },
    "home_page": "https://github.com/zencore-dobetter/zencore-errors",
    "keywords": "zencore-errors",
    "license": "MIT",
    "maintainer": "",
    "maintainer_email": "",
    "name": "zencore-errors",
    "platform": "",
    "project_url": "https://pypi.org/project/zencore-errors/",
    "release_url": "https://pypi.org/project/zencore-errors/2.0.2/",
    "requires_dist": [],
    "requires_python": "",
    "summary": "Zencore error code collection",
    "version": "2.0.2"
  },
  "releases": {
    "1.0.4": [
      {
        "comment_text": "",
        "digests": {
          "md5": "f22824df67da7137c4565e3595f27fd4",
          "sha256": "ee15e8d03bb626560b183c1a30e12013c0458f5d93da44d440fe4c305be14e1b"
        },
        "downloads": -1,
        "filename": "zencore-errors-1.0.4.tar.gz",
        "has_sig": false,
        "md5_digest": "f22824df67da7137c4565e3595f27fd4",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 2253,
        "upload_time": "2017-08-10T14:04:23",
        "url": "https://files.pythonhosted.org/packages/d0/23/e7f1efe3ed3befcf9a144e83f76b668b5addfab9198d7a01dcbf2ca6711c/zencore-errors-1.0.4.tar.gz"
      }
    ],
    "1.0.5": [
      {
        "comment_text": "",
        "digests": {
          "md5": "9df49a4be92747ea5563e7e9c9a0d986",
          "sha256": "12fb7da61d8a4272dcbae9f00fc18969d3d918c408e389ae7cb02e69bb34c65f"
        },
        "downloads": -1,
        "filename": "zencore-errors-1.0.5.tar.gz",
        "has_sig": false,
        "md5_digest": "9df49a4be92747ea5563e7e9c9a0d986",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 2274,
        "upload_time": "2017-09-18T14:52:19",
        "url": "https://files.pythonhosted.org/packages/b9/3f/79f5ec67323d44f29e46458711d88ac996ebdd451b6b9d666dd3322cbcfa/zencore-errors-1.0.5.tar.gz"
      }
    ],
    "2.0.0": [
      {
        "comment_text": "",
        "digests": {
          "md5": "77db6faa0a2f191e077c01e3bdbb6997",
          "sha256": "fe76894fc0c440704fb03015b379a56c9a6dbe2535a2832d0108de25d35d0042"
        },
        "downloads": -1,
        "filename": "zencore-errors-2.0.0.tar.gz",
        "has_sig": false,
        "md5_digest": "77db6faa0a2f191e077c01e3bdbb6997",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 2700,
        "upload_time": "2017-09-27T13:51:20",
        "url": "https://files.pythonhosted.org/packages/42/03/4770db09ff60104b95c86b6a8e18695c87f9b2191c00a545330b43f24636/zencore-errors-2.0.0.tar.gz"
      }
    ],
    "2.0.1": [
      {
        "comment_text": "",
        "digests": {
          "md5": "b01245f4a14b9b94e080f462295f819b",
          "sha256": "cc7ccd78f8b6e7fbe5f1683c8f803c56a9ca8d230f8ba7d987ec1b5e6a7b8045"
        },
        "downloads": -1,
        "filename": "zencore-errors-2.0.1.tar.gz",
        "has_sig": false,
        "md5_digest": "b01245f4a14b9b94e080f462295f819b",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 3111,
        "upload_time": "2017-09-28T14:55:59",
        "url": "https://files.pythonhosted.org/packages/0b/b5/d8cee690dfc6ec1ab6af084e5bd4f4425f0781c387267b6e5a74113a7d74/zencore-errors-2.0.1.tar.gz"
      }
    ],
    "2.0.2": [
      {
        "comment_text": "",
        "digests": {
          "md5": "bebcfe37ad5e2737bb6c3fc4bb0c55b1",
          "sha256": "c11a36806a04a26890eb68148fae8ef115407f04dc1398a7c8bc84fca9effcf5"
        },
        "downloads": -1,
        "filename": "zencore-errors-2.0.2.tar.gz",
        "has_sig": false,
        "md5_digest": "bebcfe37ad5e2737bb6c3fc4bb0c55b1",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 3294,
        "upload_time": "2017-10-10T01:58:53",
        "url": "https://files.pythonhosted.org/packages/e3/44/87e13dbeb50130d2a9515a449f7333039e50ea116d40086a84dfc6f1c1ff/zencore-errors-2.0.2.tar.gz"
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "md5": "bebcfe37ad5e2737bb6c3fc4bb0c55b1",
        "sha256": "c11a36806a04a26890eb68148fae8ef115407f04dc1398a7c8bc84fca9effcf5"
      },
      "downloads": -1,
      "filename": "zencore-errors-2.0.2.tar.gz",
      "has_sig": false,
      "md5_digest": "bebcfe37ad5e2737bb6c3fc4bb0c55b1",
      "packagetype": "sdist",
      "python_version": "source",
      "size": 3294,
      "upload_time": "2017-10-10T01:58:53",
      "url": "https://files.pythonhosted.org/packages/e3/44/87e13dbeb50130d2a9515a449f7333039e50ea116d40086a84dfc6f1c1ff/zencore-errors-2.0.2.tar.gz"
    }
  ]
}