{
  "info": {
    "author": "Huang Jiangbin",
    "author_email": "dobetter@zencore.cn",
    "bugtrack_url": null,
    "classifiers": [
      "Development Status :: 5 - Production/Stable",
      "Intended Audience :: Developers",
      "License :: OSI Approved :: MIT License",
      "Programming Language :: Python :: 3",
      "Programming Language :: Python :: 3 :: Only",
      "Topic :: Software Development :: Libraries :: Python Modules"
    ],
    "description": "zenore-errors\n=============\n\n.. image:: https://travis-ci.org/zencore-dobetter/zencore-errors.svg?branch=master\n    :target: https://travis-ci.org/zencore-dobetter/zencore-errors\n\nZencore error code collection.\n\n\n",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": 0,
      "last_month": 0,
      "last_week": 0
    },
    "home_page": "https://github.com/zencore-dobetter/zencore-errors",
    "keywords": "zencore-errors",
    "license": "MIT",
    "maintainer": "",
    "maintainer_email": "",
    "name": "zencore-errors",
    "platform": "",
    "project_url": "https://pypi.org/project/zencore-errors/",
    "release_url": "https://pypi.org/project/zencore-errors/2.0.14/",
    "requires_dist": [],
    "requires_python": "",
    "summary": "Zencore error code collection",
    "version": "2.0.14"
  },
  "releases": {
    "1.0.4": [
      {
        "comment_text": "",
        "digests": {
          "md5": "f22824df67da7137c4565e3595f27fd4",
          "sha256": "ee15e8d03bb626560b183c1a30e12013c0458f5d93da44d440fe4c305be14e1b"
        },
        "downloads": -1,
        "filename": "zencore-errors-1.0.4.tar.gz",
        "has_sig": false,
        "md5_digest": "f22824df67da7137c4565e3595f27fd4",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 2253,
        "upload_time": "2017-08-10T14:04:23",
        "url": "https://files.pythonhosted.org/packages/d0/23/e7f1efe3ed3befcf9a144e83f76b668b5addfab9198d7a01dcbf2ca6711c/zencore-errors-1.0.4.tar.gz"
      }
    ],
    "1.0.5": [
      {
        "comment_text": "",
        "digests": {
          "md5": "9df49a4be92747ea5563e7e9c9a0d986",
          "sha256": "12fb7da61d8a4272dcbae9f00fc18969d3d918c408e389ae7cb02e69bb34c65f"
        },
        "downloads": -1,
        "filename": "zencore-errors-1.0.5.tar.gz",
        "has_sig": false,
        "md5_digest": "9df49a4be92747ea5563e7e9c9a0d986",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 2274,
        "upload_time": "2017-09-18T14:52:19",
        "url": "https://files.pythonhosted.org/packages/b9/3f/79f5ec67323d44f29e46458711d88ac996ebdd451b6b9d666dd3322cbcfa/zencore-errors-1.0.5.tar.gz"
      }
    ],
    "2.0.14": [
      {
        "comment_text": "",
        "digests": {
          "md5": "9c3ee24b191f051f19b6b87498f608fd",
          "sha256": "36de398fdf02551c59c3575e155c41ef718e508b7847f51ab1961ab991dde97e"
        },
        "downloads": -1,
        "filename": "zencore-errors-2.0.14.tar.gz",
        "has_sig": false,
        "md5_digest": "9c3ee24b191f051f19b6b87498f608fd",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 3696,
        "upload_time": "2017-10-31T14:44:03",
        "url": "https://files.pythonhosted.org/packages/ab/7c/85cebfffdf3b9164d572931859c4319e145185558db6204084446bf549ec/zencore-errors-2.0.14.tar.gz"
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "md5": "9c3ee24b191f051f19b6b87498f608fd",
        "sha256": "36de398fdf02551c59c3575e155c41ef718e508b7847f51ab1961ab991dde97e"
      },
      "downloads": -1,
      "filename": "zencore-errors-2.0.14.tar.gz",
      "has_sig": false,
      "md5_digest": "9c3ee24b191f051f19b6b87498f608fd",
      "packagetype": "sdist",
      "python_version": "source",
      "size": 3696,
      "upload_time": "2017-10-31T14:44:03",
      "url": "https://files.pythonhosted.org/packages/ab/7c/85cebfffdf3b9164d572931859c4319e145185558db6204084446bf549ec/zencore-errors-2.0.14.tar.gz"
    }
  ]
}